#include "ui/AIImageDetectorPanel.h"
#include "utils/Logger.h"
#include "detectors/HiveImageModerator.h"
#include <QFileDialog>
#include <QFont>
#include <QMessageBox>
#include <QImageReader>
#include <QFile>
#include <QtConcurrent>
#include <QFutureWatcher>
#include <QTimer>

namespace ModAI {

AIImageDetectorPanel::AIImageDetectorPanel(QWidget* parent)
    : QWidget(parent)
    , imageDisplay_(nullptr)
    , selectButton_(nullptr)
    , analyzeButton_(nullptr)
    , clearButton_(nullptr)
    , resultLabel_(nullptr)
    , scoreBar_(nullptr)
    , detailsLabel_(nullptr)
    , statusLabel_(nullptr)
    , loadingTimer_(nullptr)
    , loadingDots_(0) {
    setupUI();
}

void AIImageDetectorPanel::initialize(std::shared_ptr<ImageModerator> imageModerator) {
    imageModerator_ = imageModerator;
    
    if (imageModerator_) {
        statusLabel_->setText("AI detector ready");
        selectButton_->setEnabled(true);
    } else {
        statusLabel_->setText("AI detector not available");
        selectButton_->setEnabled(false);
    }
}

void AIImageDetectorPanel::setupUI() {
    auto* layout = new QVBoxLayout(this);
    
    // Header
    auto* headerLabel = new QLabel("AI Image Detector");
    QFont headerFont = headerLabel->font();
    headerFont.setPointSize(14);
    headerFont.setBold(true);
    headerLabel->setFont(headerFont);
    layout->addWidget(headerLabel);
    
    auto* infoLabel = new QLabel(
        "Upload an image to analyze whether it was generated by AI. "
        "The detector uses advanced computer vision models to identify AI-generated imagery."
    );
    infoLabel->setWordWrap(true);
    infoLabel->setStyleSheet("color: #666; margin-bottom: 15px;");
    layout->addWidget(infoLabel);
    
    // Image display
    imageDisplay_ = new QLabel;
    imageDisplay_->setMinimumSize(400, 400);
    imageDisplay_->setMaximumSize(600, 600);
    imageDisplay_->setAlignment(Qt::AlignCenter);
    imageDisplay_->setStyleSheet(
        "QLabel { "
        "  border: 2px dashed #ccc; "
        "  border-radius: 10px; "
        "  background-color: #f9f9f9; "
        "  color: #999; "
        "  font-size: 14pt; "
        "}"
    );
    imageDisplay_->setText("No image loaded\n\nClick 'Select Image' to choose a file");
    imageDisplay_->setScaledContents(false);
    layout->addWidget(imageDisplay_, 1, Qt::AlignCenter);
    
    // Buttons
    auto* buttonLayout = new QHBoxLayout;
    selectButton_ = new QPushButton("📁 Select Image");
    selectButton_->setMinimumHeight(40);
    selectButton_->setStyleSheet(
        "QPushButton { "
        "  background-color: #6c757d; "
        "  color: white; "
        "  border: none; "
        "  border-radius: 5px; "
        "  font-weight: bold; "
        "  padding: 10px 20px; "
        "}"
        "QPushButton:hover { background-color: #5a6268; }"
        "QPushButton:pressed { background-color: #545b62; }"
    );
    
    analyzeButton_ = new QPushButton("Analyze Image");
    analyzeButton_->setMinimumHeight(45);
    analyzeButton_->setEnabled(false);
    analyzeButton_->setStyleSheet(
        "QPushButton { "
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #667eea, stop:1 #764ba2); "
        "  color: white; "
        "  border: none; "
        "  border-radius: 8px; "
        "  font-weight: bold; "
        "  font-size: 13pt; "
        "  padding: 12px 24px; "
        "}"
        "QPushButton:hover { "
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #764ba2, stop:1 #667eea); "
        "}"
        "QPushButton:pressed { background: #5a3d7a; }"
        "QPushButton:disabled { "
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #b8c5f2, stop:1 #c5b8d9); "
        "}"
    );
    
    clearButton_ = new QPushButton("Clear");
    clearButton_->setMinimumHeight(40);
    clearButton_->setEnabled(false);
    
    buttonLayout->addWidget(selectButton_);
    buttonLayout->addWidget(analyzeButton_);
    buttonLayout->addWidget(clearButton_);
    buttonLayout->addStretch();
    layout->addLayout(buttonLayout);
    
    // Results section
    auto* resultsLabel = new QLabel("Analysis Results:");
    resultsLabel->setStyleSheet("font-weight: bold; margin-top: 20px; margin-bottom: 10px;");
    layout->addWidget(resultsLabel);
    
    // Result display with score bar
    resultLabel_ = new QLabel("No analysis yet");
    resultLabel_->setStyleSheet(
        "background-color: #f5f5f5; "
        "border: 1px solid #ddd; "
        "border-radius: 5px; "
        "padding: 15px; "
        "font-size: 14pt; "
        "font-weight: bold;"
    );
    resultLabel_->setAlignment(Qt::AlignCenter);
    layout->addWidget(resultLabel_);
    
    scoreBar_ = new QProgressBar;
    scoreBar_->setRange(0, 100);
    scoreBar_->setValue(0);
    scoreBar_->setTextVisible(true);
    scoreBar_->setFormat("AI Score: %p%");
    scoreBar_->setMinimumHeight(30);
    scoreBar_->setStyleSheet(
        "QProgressBar { "
        "  border: 2px solid #ddd; "
        "  border-radius: 5px; "
        "  text-align: center; "
        "  font-weight: bold; "
        "}"
        "QProgressBar::chunk { "
        "  background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, "
        "    stop:0 #00cc00, stop:0.5 #ffcc00, stop:1 #cc0000); "
        "}"
    );
    layout->addWidget(scoreBar_);
    
    detailsLabel_ = new QLabel("");
    detailsLabel_->setWordWrap(true);
    detailsLabel_->setStyleSheet("color: #666; margin-top: 10px; padding: 10px;");
    layout->addWidget(detailsLabel_);
    
    // Status
    statusLabel_ = new QLabel("Ready");
    statusLabel_->setStyleSheet("color: #666; margin-top: 10px;");
    layout->addWidget(statusLabel_);
    
    // Connections
    connect(selectButton_, &QPushButton::clicked, this, &AIImageDetectorPanel::onSelectImage);
    connect(analyzeButton_, &QPushButton::clicked, this, &AIImageDetectorPanel::onAnalyzeImage);
    connect(clearButton_, &QPushButton::clicked, this, &AIImageDetectorPanel::onClearImage);
}

void AIImageDetectorPanel::onSelectImage() {
    QString fileName = QFileDialog::getOpenFileName(
        this,
        "Select Image",
        QDir::homePath(),
        "Images (*.png *.jpg *.jpeg *.gif *.bmp *.webp);;All Files (*.*)"
    );
    
    if (fileName.isEmpty()) {
        return;
    }
    
    currentImagePath_ = fileName;
    displayImage(fileName);
    
    analyzeButton_->setEnabled(true);
    clearButton_->setEnabled(true);
    statusLabel_->setText("Image loaded: " + QFileInfo(fileName).fileName());
    
    // Reset results
    resultLabel_->setText("No analysis yet");
    scoreBar_->setValue(0);
    detailsLabel_->clear();
}

void AIImageDetectorPanel::displayImage(const QString& path) {
    QPixmap pixmap(path);
    
    if (pixmap.isNull()) {
        imageDisplay_->setText("Error loading image");
        statusLabel_->setText("Failed to load image");
        return;
    }
    
    // Scale to fit display while maintaining aspect ratio
    QPixmap scaled = pixmap.scaled(imageDisplay_->size(), Qt::KeepAspectRatio, Qt::SmoothTransformation);
    imageDisplay_->setPixmap(scaled);
    imageDisplay_->setStyleSheet(
        "QLabel { "
        "  border: 2px solid #0066cc; "
        "  border-radius: 10px; "
        "  background-color: #f9f9f9; "
        "}"
    );
}

void AIImageDetectorPanel::onAnalyzeImage() {
    if (currentImagePath_.isEmpty()) {
        statusLabel_->setText("Please select an image first");
        return;
    }
    
    if (!imageModerator_) {
        statusLabel_->setText("AI detector not available");
        return;
    }
    
    statusLabel_->setText("Analyzing image with AI...");
    analyzeButton_->setEnabled(false);
    selectButton_->setEnabled(false);
    clearButton_->setEnabled(false);
    
    // Animate button with pulsing dots
    loadingDots_ = 0;
    loadingTimer_ = new QTimer(this);
    connect(loadingTimer_, &QTimer::timeout, [this]() {
        loadingDots_ = (loadingDots_ + 1) % 4;
        QString dots(loadingDots_, '.');
        QString spaces(3 - loadingDots_, ' ');
        analyzeButton_->setText("Analyzing" + dots + spaces);
    });
    loadingTimer_->start(400);
    
    // Prepare data for background processing
    QString imagePath = currentImagePath_;
    auto moderator = imageModerator_;
    
    auto* watcher = new QFutureWatcher<std::pair<float, QString>>(this);
    connect(watcher, &QFutureWatcher<std::pair<float, QString>>::finished, [this, watcher]() {
        if (loadingTimer_) {
            loadingTimer_->stop();
            loadingTimer_->deleteLater();
            loadingTimer_ = nullptr;
        }
        
        try {
            auto result = watcher->result();
            onAnalysisComplete(result.first, result.second);
        } catch (const std::exception& e) {
            statusLabel_->setText("Error: " + QString::fromStdString(e.what()));
            Logger::error("AI image detection error: " + std::string(e.what()));
            
            // Re-enable UI
            analyzeButton_->setText("Analyze Image");
            analyzeButton_->setEnabled(true);
            selectButton_->setEnabled(true);
            clearButton_->setEnabled(true);
        }
        
        watcher->deleteLater();
    });
    
    // Start async analysis
    QFuture<std::pair<float, QString>> future = QtConcurrent::run([moderator, imagePath]() -> std::pair<float, QString> {
        // Load image file as bytes
        QFile file(imagePath);
        if (!file.open(QIODevice::ReadOnly)) {
            throw std::runtime_error("Failed to open image file");
        }
        
        QByteArray imageData = file.readAll();
        file.close();
        
        std::vector<uint8_t> imageBytes(imageData.begin(), imageData.end());
        
        // Determine MIME type
        std::string mimeType = "image/jpeg";
        if (imagePath.endsWith(".png", Qt::CaseInsensitive)) {
            mimeType = "image/png";
        } else if (imagePath.endsWith(".gif", Qt::CaseInsensitive)) {
            mimeType = "image/gif";
        }
        
        // Moderate/analyze the image
        auto result = moderator->analyzeImage(imageBytes, mimeType);
        
        // Extract AI detection score
        float aiScore = 0.0f;
        std::string detailsText;
        
        for (const auto& [category, score] : result.labels) {
            if (category == "ai_generated" || category == "ai-generated") {
                aiScore = static_cast<float>(score);
                detailsText = "AI-Generated class detected by Hive API";
                break;
            }
        }
        
        // If no explicit AI class, use a heuristic
        if (aiScore == 0.0f && !result.labels.empty()) {
            detailsText = "Estimating based on visual patterns. ";
            detailsText += "Note: For accurate AI detection, Hive API should include 'ai_generated' class.";
            aiScore = 0.3f; // Placeholder
        }
        
        return std::make_pair(aiScore, QString::fromStdString(detailsText));
    });
    
    watcher->setFuture(future);
}

void AIImageDetectorPanel::onAnalysisComplete(float aiScore, const QString& details) {
    // Reset button text
    analyzeButton_->setText("Analyze Image");
    
    // Update UI with results
    updateResults(aiScore, details.toStdString());
    emit analysisComplete(aiScore);
    
    // Re-enable UI
    analyzeButton_->setEnabled(true);
    selectButton_->setEnabled(true);
    clearButton_->setEnabled(true);
}

void AIImageDetectorPanel::onClearImage() {
    currentImagePath_.clear();
    imageDisplay_->clear();
    imageDisplay_->setText("No image loaded\n\nClick 'Select Image' to choose a file");
    imageDisplay_->setStyleSheet(
        "QLabel { "
        "  border: 2px dashed #ccc; "
        "  border-radius: 10px; "
        "  background-color: #f9f9f9; "
        "  color: #999; "
        "  font-size: 14pt; "
        "}"
    );
    
    resultLabel_->setText("No analysis yet");
    scoreBar_->setValue(0);
    detailsLabel_->clear();
    statusLabel_->setText("Cleared");
    
    analyzeButton_->setEnabled(false);
    clearButton_->setEnabled(false);
}

void AIImageDetectorPanel::updateResults(float aiScore, const std::string& details) {
    // Convert to percentage
    int scorePercent = static_cast<int>(aiScore * 100);
    scoreBar_->setValue(scorePercent);
    
    // Determine verdict
    QString verdict;
    QString color;
    
    if (aiScore >= 0.8f) {
        verdict = "Likely AI-Generated";
        color = "#cc0000"; // Red
    } else if (aiScore >= 0.5f) {
        verdict = "Possibly AI-Generated";
        color = "#ff9900"; // Orange
    } else if (aiScore >= 0.3f) {
        verdict = "Mixed/Uncertain";
        color = "#ffcc00"; // Yellow
    } else {
        verdict = "Likely Real/Authentic";
        color = "#00cc00"; // Green
    }
    
    resultLabel_->setText(verdict);
    resultLabel_->setStyleSheet(
        QString("background-color: %1; "
                "color: white; "
                "border: 1px solid #ddd; "
                "border-radius: 5px; "
                "padding: 15px; "
                "font-size: 14pt; "
                "font-weight: bold;").arg(color)
    );
    
    // Details
    QString detailsText = QString(
        "<b>Confidence Score:</b> %1%<br>"
        "<b>Interpretation:</b><br>"
        "• 0-30%: Likely authentic/real image<br>"
        "• 30-50%: Mixed or uncertain origin<br>"
        "• 50-80%: Possibly AI-generated<br>"
        "• 80-100%: Likely AI-generated<br><br>"
        "<i>Note: AI image detection analyzes visual patterns, artifacts, and inconsistencies. "
        "Results depend on the sophistication of the generation model.</i>"
    ).arg(scorePercent);
    
    if (!details.empty()) {
        detailsText += "<br><br><b>Details:</b><br>" + 
                      QString::fromStdString(details).toHtmlEscaped();
    }
    
    detailsLabel_->setText(detailsText);
    statusLabel_->setText("Analysis complete");
}

void AIImageDetectorPanel::setTheme(bool isDark) {
    if (isDark) {
        // Dark theme - update button style but keep gradient
        analyzeButton_->setStyleSheet(
            "QPushButton { "
            "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #667eea, stop:1 #764ba2); "
            "  color: white; "
            "  border: none; "
            "  border-radius: 8px; "
            "  font-weight: bold; "
            "  font-size: 13pt; "
            "  padding: 12px 24px; "
            "}"
            "QPushButton:hover { "
            "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #764ba2, stop:1 #667eea); "
            "}"
            "QPushButton:pressed { background: #5a3d7a; }"
            "QPushButton:disabled { background: #555; color: #999; }"
        );
        
    } else {
        // Light theme
        analyzeButton_->setStyleSheet(
            "QPushButton { "
            "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #667eea, stop:1 #764ba2); "
            "  color: white; "
            "  border: none; "
            "  border-radius: 8px; "
            "  font-weight: bold; "
            "  font-size: 13pt; "
            "  padding: 12px 24px; "
            "}"
            "QPushButton:hover { "
            "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #764ba2, stop:1 #667eea); "
            "}"
            "QPushButton:pressed { background: #5a3d7a; }"
            "QPushButton:disabled { "
            "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #b8c5f2, stop:1 #c5b8d9); "
            "}"
        );
    }
}

} // namespace ModAI
