#pragma once

#include <QWidget>
#include <QLabel>
#include <QPushButton>
#include <QProgressBar>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPixmap>
#include <QTimer>
#include <QResizeEvent>
#include <memory>
#include "detectors/ImageModerator.h"

namespace ModAI {

/**
 * @brief Panel for detecting AI-generated images
 * 
 * Allows users to upload images and get an AI-detection score
 * showing the likelihood that the image was generated by AI.
 * Also checks for embedded metadata from ModAI image generation.
 */
class AIImageDetectorPanel : public QWidget {
    Q_OBJECT

public:
    explicit AIImageDetectorPanel(QWidget* parent = nullptr);
    ~AIImageDetectorPanel() = default;

    /**
     * @brief Initialize with image moderator (Hive AI includes AI detection)
     */
    void initialize(std::shared_ptr<ImageModerator> imageModerator);

public:
    void setTheme(bool isDark);
    
    /**
     * @brief Extract AI generation metadata from image file
     * @return Source model identifier or empty string if not found
     */
    static QString extractImageSource(const QString& imagePath);

signals:
    void analysisComplete(float score);

private slots:
    void onSelectImage();
    void onAnalyzeImage();
    void onClearImage();
    void onAnalysisComplete(float aiScore, const QString& details, const QString& source);

private:
    void setupUI();
    void updateResults(float aiScore, const std::string& details, const QString& source = QString());
    void displayImage(const QString& path);

protected:
    void resizeEvent(QResizeEvent* event) override;

private:
    QLabel* imageDisplay_;
    QPushButton* selectButton_;
    QPushButton* analyzeButton_;
    QPushButton* clearButton_;
    QLabel* resultLabel_;
    QProgressBar* scoreBar_;
    QLabel* detailsLabel_;
    QLabel* sourceLabel_;  // New: shows AI generation source if detected
    QLabel* statusLabel_;
    QTimer* loadingTimer_;
    int loadingDots_;

    std::shared_ptr<ImageModerator> imageModerator_;
    QString currentImagePath_;
    QPixmap originalPixmap_;  // Store original for resizing
};

} // namespace ModAI
