#pragma once

#include <QWidget>
#include <QTextEdit>
#include <QPushButton>
#include <QLabel>
#include <QProgressBar>
#include <QVBoxLayout>
#include <QTimer>
#include <memory>
#include "detectors/TextDetector.h"

namespace ModAI {

/**
 * @brief Panel for detecting AI-generated text
 * 
 * Allows users to paste text and get an AI-detection score
 * showing the likelihood that the text was generated by AI.
 */
class AITextDetectorPanel : public QWidget {
    Q_OBJECT

public:
    explicit AITextDetectorPanel(QWidget* parent = nullptr);
    ~AITextDetectorPanel() = default;

    /**
     * @brief Initialize with text detector
     */
    void initialize(std::shared_ptr<TextDetector> textDetector);

public:
    void setTheme(bool isDark);

signals:
    void analysisComplete(float score);

private slots:
    void onAnalyzeText();
    void onClearText();
    void onAnalysisComplete(float aiScore, const QString& label);

private:
    void setupUI();
    void updateResults(float aiScore, const std::string& details);

    QTextEdit* textInput_;
    QPushButton* analyzeButton_;
    QPushButton* clearButton_;
    QLabel* resultLabel_;
    QProgressBar* scoreBar_;
    QLabel* detailsLabel_;
    QLabel* statusLabel_;
    QTimer* loadingTimer_;
    int loadingDots_;
    QString currentText_;  // Store text for watermark check after analysis

    std::shared_ptr<TextDetector> textDetector_;
};

} // namespace ModAI
